# Render Configuration
# This file tells Render how to build and run your application

# Build Command
build: npm install

# Start Command
start: npm start

# Environment
node: 18

# Health Check
healthCheckPath: /health

# Auto Deploy
autoDeploy: true
